export const Pagelink = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/products" },
  { label: "Cart", href: "/cart" },
];

export const productList = [
  {
    name: "Oak Wood Dining Table",
    price: 25000,
    img: "/images/oak-dining.jpg",
    desc: "Solid oak wood dining table with premium finish.",
    category: "furniture",
    stock: 12,
  },
  {
    name: "Velvet Armchair",
    price: 8500,
    img: "/images/velvet-armchair.jpg",
    desc: "Soft velvet armchair with ergonomic support.",
    category: "seating",
    stock: 8,
  },
  {
    name: "Mahogany Bookshelf",
    price: 15000,
    img: "/images/mahogany-shelf.jpg",
    desc: "Classic 5-tier mahogany wood bookshelf.",
    category: "storage",
    stock: 5,
  },
  {
    name: "Minimalist Coffee Table",
    price: 4500,
    img: "/images/coffee-table.jpg",
    desc: "Sleek pine wood coffee table for modern homes.",
    category: "furniture",
    stock: 20,
  },
  {
    name: "Leather 3-Seater Sofa",
    price: 45000,
    img: "/images/leather-sofa.jpg",
    desc: "Genuine Italian leather sofa in chestnut brown.",
    category: "seating",
    stock: 3,
  },
  {
    name: "Walnut Bed Frame",
    price: 32000,
    img: "/images/walnut-bed.jpg",
    desc: "King size walnut wood frame with headboard.",
    category: "bedroom",
    stock: 7,
  },
  {
    name: "Industrial Office Desk",
    price: 12000,
    img: "/images/office-desk.jpg",
    desc: "Steel frame desk with reclaimed wood top.",
    category: "office",
    stock: 15,
  },
  {
    name: "Teak Garden Chair",
    price: 3500,
    img: "/images/garden-chair.jpg",
    desc: "Weather-resistant teak wood chair for outdoors.",
    category: "outdoor",
    stock: 25,
  },
  {
    name: "Ceramic Table Lamp",
    price: 2200,
    img: "/images/table-lamp.jpg",
    desc: "Handcrafted ceramic base with linen shade.",
    category: "decor",
    stock: 40,
  },
  {
    name: "Bamboo Shoe Rack",
    price: 1800,
    img: "/images/shoe-rack.jpg",
    desc: "Eco-friendly 3-tier bamboo shoe organizer.",
    category: "storage",
    stock: 30,
  },
  {
    name: "Scandinavian Sideboard",
    price: 18500,
    img: "/images/sideboard.jpg",
    desc: "Light oak sideboard with sliding doors.",
    category: "storage",
    stock: 6,
  },
  {
    name: "Memory Foam Mattress",
    price: 21000,
    img: "/images/mattress.jpg",
    desc: "Orthopedic memory foam for deep sleep.",
    category: "bedroom",
    stock: 10,
  },
  {
    name: "Ergonomic Mesh Chair",
    price: 9500,
    img: "/images/mesh-chair.jpg",
    desc: "Breathable mesh back with lumbar support.",
    category: "office",
    stock: 22,
  },
  {
    name: "Marble Top End Table",
    price: 7200,
    img: "/images/end-table.jpg",
    desc: "White marble top with gold-finished legs.",
    category: "furniture",
    stock: 14,
  },
  {
    name: "Floating Wall Shelves",
    price: 1500,
    img: "/images/floating-shelves.jpg",
    desc: "Set of 3 rustic wood floating shelves.",
    category: "storage",
    stock: 50,
  },
  {
    name: "Tufted Ottoman",
    price: 3800,
    img: "/images/ottoman.jpg",
    desc: "Grey fabric tufted ottoman with storage.",
    category: "seating",
    stock: 18,
  },
  {
    name: "Pine Wood Wardrobe",
    price: 28000,
    img: "/images/wardrobe.jpg",
    desc: "Large 2-door wardrobe with hanging rail.",
    category: "bedroom",
    stock: 4,
  },
  {
    name: "Kitchen Bar Stool",
    price: 2900,
    img: "/images/bar-stool.jpg",
    desc: "Adjustable swivel stool with chrome base.",
    category: "seating",
    stock: 24,
  },
  {
    name: "Full Length Mirror",
    price: 5400,
    img: "/images/mirror.jpg",
    desc: "Solid wood framed floor standing mirror.",
    category: "decor",
    stock: 11,
  },
  {
    name: "Glass TV Stand",
    price: 8900,
    img: "/images/tv-stand.jpg",
    desc: "Tempered glass shelves with black metal frame.",
    category: "furniture",
    stock: 9,
  },
  {
    name: "Rattan Lounge Chair",
    price: 11000,
    img: "/images/rattan-chair.jpg",
    desc: "Hand-woven rattan chair with cushions.",
    category: "seating",
    stock: 7,
  },
  {
    name: "Maple Nightstand",
    price: 4200,
    img: "/images/nightstand.jpg",
    desc: "Compact maple wood bedside table with drawer.",
    category: "bedroom",
    stock: 16,
  },
  {
    name: "L-Shaped Sectional",
    price: 68000,
    img: "/images/sectional.jpg",
    desc: "Large charcoal fabric sectional for families.",
    category: "seating",
    stock: 2,
  },
  {
    name: "Geometric Wool Rug",
    price: 7500,
    img: "/images/rug.jpg",
    desc: "5x7 hand-tufted wool rug with pattern.",
    category: "decor",
    stock: 13,
  },
  {
    name: "Drafting Stool",
    price: 4800,
    img: "/images/drafting-stool.jpg",
    desc: "Height-adjustable stool for artists and architects.",
    category: "office",
    stock: 10,
  },
  {
    name: "Cedar Chest",
    price: 13500,
    img: "/images/cedar-chest.jpg",
    desc: "Aromatic cedar wood storage trunk.",
    category: "storage",
    stock: 5,
  },
  {
    name: "Kitchen Island",
    price: 22000,
    img: "/images/kitchen-island.jpg",
    desc: "Portable island with butcher block top.",
    category: "furniture",
    stock: 4,
  },
  {
    name: "Recliner Sofa",
    price: 19500,
    img: "/images/recliner.jpg",
    desc: "Single motor power recliner in microfiber.",
    category: "seating",
    stock: 6,
  },
  {
    name: "Floor Lamp",
    price: 3100,
    img: "/images/floor-lamp.jpg",
    desc: "Arc-style floor lamp with marble base.",
    category: "decor",
    stock: 20,
  },
  {
    name: "Vanity Table",
    price: 14000,
    img: "/images/vanity.jpg",
    desc: "Makeup vanity with LED mirror and drawers.",
    category: "bedroom",
    stock: 8,
  },
  {
    name: "Round Dining Table",
    price: 17500,
    img: "/images/round-table.jpg",
    desc: "4-seater pedestal table in cherry wood.",
    category: "furniture",
    stock: 10,
  },
  {
    name: "Bean Bag Chair",
    price: 2500,
    img: "/images/bean-bag.jpg",
    desc: "Large XXL bean bag with velvet cover.",
    category: "seating",
    stock: 35,
  },
  {
    name: "Wine Rack",
    price: 3800,
    img: "/images/wine-rack.jpg",
    desc: "Wall-mounted wood rack for 12 bottles.",
    category: "storage",
    stock: 15,
  },
  {
    name: "Nesting Tables",
    price: 5200,
    img: "/images/nesting-tables.jpg",
    desc: "Set of 3 stackable wood and metal tables.",
    category: "furniture",
    stock: 12,
  },
  {
    name: "Coat Hanger Stand",
    price: 2100,
    img: "/images/coat-stand.jpg",
    desc: "Freestanding wooden coat rack with 8 hooks.",
    category: "decor",
    stock: 25,
  },
  {
    name: "Folding Desk",
    price: 4500,
    img: "/images/folding-desk.jpg",
    desc: "Space-saving folding desk for small rooms.",
    category: "office",
    stock: 18,
  },
  {
    name: "Hammock Chair",
    price: 3200,
    img: "/images/hammock.jpg",
    desc: "Cotton rope hanging chair for indoor/outdoor.",
    category: "seating",
    stock: 14,
  },
  {
    name: "Daybed with Trundle",
    price: 26500,
    img: "/images/daybed.jpg",
    desc: "Twin daybed with pull-out guest bed.",
    category: "bedroom",
    stock: 3,
  },
  {
    name: "Antique Clock",
    price: 6800,
    img: "/images/clock.jpg",
    desc: "Large wooden wall clock with Roman numerals.",
    category: "decor",
    stock: 9,
  },
  {
    name: "Media Console",
    price: 15500,
    img: "/images/console.jpg",
    desc: "Mid-century modern TV unit with oak finish.",
    category: "furniture",
    stock: 7,
  },
  {
    name: "Patio Sofa Set",
    price: 55000,
    img: "/images/patio-set.jpg",
    desc: "4-piece wicker set with sunproof cushions.",
    category: "outdoor",
    stock: 5,
  },
  {
    name: "Desk Organizer",
    price: 950,
    img: "/images/organizer.jpg",
    desc: "Bamboo desk caddy for pens and accessories.",
    category: "office",
    stock: 100,
  },
  {
    name: "Jewelry Armoire",
    price: 7800,
    img: "/images/jewelry-box.jpg",
    desc: "Standing mirror with jewelry storage inside.",
    category: "bedroom",
    stock: 12,
  },
  {
    name: "Bench with Cubbies",
    price: 6400,
    img: "/images/entry-bench.jpg",
    desc: "Entryway bench with 3 storage cubbies.",
    category: "storage",
    stock: 15,
  },
  {
    name: "Corner Bookshelf",
    price: 5900,
    img: "/images/corner-shelf.jpg",
    desc: "Tall zig-zag corner shelf in espresso.",
    category: "storage",
    stock: 20,
  },
  {
    name: "Standing Desk",
    price: 28000,
    img: "/images/standing-desk.jpg",
    desc: "Dual motor electric height adjustable desk.",
    category: "office",
    stock: 6,
  },
  {
    name: "Dining Chair Set",
    price: 12500,
    img: "/images/dining-chairs.jpg",
    desc: "Set of 4 upholstered dining chairs.",
    category: "seating",
    stock: 10,
  },
  {
    name: "Couch Protector",
    price: 1500,
    img: "/images/couch-cover.jpg",
    desc: "Waterproof slipcover for 3-seater sofas.",
    category: "decor",
    stock: 45,
  },
  {
    name: "Kids Bunk Bed",
    price: 34000,
    img: "/images/bunk-bed.jpg",
    desc: "Solid pine wood bunk bed with safety rail.",
    category: "bedroom",
    stock: 4,
  },
  {
    name: "Magazine Rack",
    price: 1200,
    img: "/images/magazine-rack.jpg",
    desc: "Sleek metal and wood magazine holder.",
    category: "decor",
    stock: 30,
  },
];
