import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SessionWrapper from "../provider";
import CartLoader from "@/components/cart/cartLoader";
import { getServerSession } from "next-auth";
import { authOptions } from "@/features/useAuth";
import { redirect } from "next/navigation";
import SignOutBtn from "@/components/signoutButton";
import AdminTabs from "@/components/admin/adminTab";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WoodWork-Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
  }
  if (session.user.role !== "admin") {
    redirect("/");
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionWrapper>
          <CartLoader />
          <div className="flex justify-between">
            <h1>WoodWork</h1>
            <SignOutBtn url={"/"} />
          </div>
          <div className="my-5">
            <h1>Hello Admin</h1>
          </div>
          <AdminTabs />
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
